server:
  port: 8083
spring:
  datasource:
    #url: jdbc:mysql://finemine.ru:3306/admin_mobileteater?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: admin_mobileteater
    #password: wqwlIDfRSN

    #url: jdbc:postgresql://localhost:5432/mt_main?user=postgres&password=oleg57
    #driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://finemine.su:5432/mt_main?user=pterodactyl&password=Pl3453Ch4n63M3!
    driverClassName: org.postgresql.Driver

    #driverClassName: org.h2.Driver
#    hikari:
#      catalog: 'sql4501069'
#  hibernate.dialect.Dialect: org.hibernate.dialect.PostgreSQL95Dialect
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: 'public'
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
    default-schema: 'public'
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
front:
  web:
    url: http://localhost:3000